// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: sq_t

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain(lv_event_t *e);
lv_obj_t *ui_ScreenMain;
lv_obj_t *ui_ArcRpm;
lv_obj_t *ui_rpm;
lv_obj_t *ui_ArcClt;
lv_obj_t *ui_LabelRpm;
lv_obj_t *ui_Spd;
lv_obj_t *ui_LabelSpd;
lv_obj_t *ui_Clt;
lv_obj_t *ui_deg;
lv_obj_t *ui_Label8;


// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
void ui_event_ScreenSettings(lv_event_t *e);
lv_obj_t *ui_ScreenSettings;
lv_obj_t *ui_Label9;
void ui_event_Slider1(lv_event_t *e);
lv_obj_t *ui_Slider1;
lv_obj_t *ui_Label10;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenMain(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_ScreenSettings_screen_init);
    _ui_screen_delete(&ui_ScreenMain);
  }
}
void ui_event_ScreenSettings(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
    lv_indev_wait_release(lv_indev_active());
    _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_ScreenMain_screen_init);
    _ui_screen_delete(&ui_ScreenSettings);
  }
}
void ui_event_Slider1(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_VALUE_CHANGED) {
    setBrightness(e);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  lv_disp_t *dispp = lv_display_get_default();
  lv_theme_t *theme = lv_theme_simple_init(dispp);
  lv_disp_set_theme(dispp, theme);
  ui_ScreenMain_screen_init();
  ui_ScreenSettings_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_ScreenMain);
}
