// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: sq_t

#ifndef _SQ_T_UI_H
#define _SQ_T_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
void ui_event_ScreenMain( lv_event_t * e);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_ArcRpm;
extern lv_obj_t *ui_rpm;
extern lv_obj_t *ui_ArcClt;
extern lv_obj_t *ui_LabelRpm;
extern lv_obj_t *ui_Spd;
extern lv_obj_t *ui_LabelSpd;
extern lv_obj_t *ui_Clt;
extern lv_obj_t *ui_deg;
extern lv_obj_t *ui_Label8;
// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
void ui_event_ScreenSettings( lv_event_t * e);
extern lv_obj_t *ui_ScreenSettings;
extern lv_obj_t *ui_Label9;
void ui_event_Slider1( lv_event_t * e);
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
